name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - run: make container
  lint:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0
      - run: sudo apt-get update && sudo apt-get install -y libbpf-dev libxdp-dev
      - uses: cpp-linter/cpp-linter-action@v2.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 20
          style: "file"
          tidy-checks: ""
          ignore-tidy: src
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
